In [41]:
import matplotlib.pyplot as plt
import numpy as np
import math as m
from sympy import *

def matrix(): #Функция задания матрицы 
    coef_a = 10.
    A = np.zeros((100, 100))
    F = np.zeros(100)
    for i in range(0,100,1):
        F[i] = 100 - i
        for j in range(0,100,1):
            if(i == 0):
                A[i][j] = 1
            elif((i > 0) & (i <= 98)):
                if(i == j):
                    A[i][j] = coef_a * 1.
                    A[i][j-1] = 1.
                    A[i][j+1] = 1.
                    continue
            else:
                if(j > 97):
                    A[i][j] = 1.
    return A, F
A,F = matrix() #Задание матрицы

print("Матрица коэффициентов - ",'\n',A)
print("Значения - ",F)

X = np.zeros(100)
saveA = A.copy() # Копирование матрицы А
saveF = F.copy() # Копирование матрицы F

m = np.linalg.norm(A, 1) * np.linalg.norm(np.linalg.inv(A) , 1) # вычесление числа обусловленности      

lambdmin = 1000000000000 # Перемнная для лямбда минимальное
lambdmax = -1000000000000 # Переменная для лямбда максимальное

lambds = list() # задание пустого списка всех лямбд
lambds = np.linalg.eig(A) # задания списка всех лямбд

for k in range (1, 100, 1): #Метод Гаусса(делем верхнетреугольную матрицу А, и заполняем матрицу F новыми значениями)
    for i in range(k, 100, 1):
        aij = A[i][k - 1]
        for j in range(0, len(A[i] - 1), 1):
            A[i][j] = A[i][j] - A[k - 1][j] * aij  / A[k - 1][k - 1]
        F[i] = F[i] - F[i - 1] / A[k - 1][k - 1] * aij

for i in range(99, -1, -1): # Подставляем Х в нашу систему снизу вверх
    sum = 0.
    for j in range(100):
        sum += A[i][j] * X[j]
    X[i] = (F[i] - sum) / A[i][i]
    
R = abs(saveF - np.dot(saveA, X)) # Нахождение вектора невязки
    
for i in (lambds[0]): # нахождение минимальной и максимальной лямбды
    if (i >= lambdmax):
        lambdmax = i
    if(i <= lambdmin):
        lambdmin = i
                            
print("Лямбда минимальная  = ", lambdmin,"\n", "Лямбда максиммальная = ", lambdmax)
print ("Число обусловленности = ", m)
print("Список значений аргументов = ","\n", X) 
print("Вектор невязки = ",'\n', np.linalg.norm(R,1))

Матрица коэффициентов -  
 [[ 1.  1.  1. ...  1.  1.  1.]
 [ 1. 10.  1. ...  0.  0.  0.]
 [ 0.  1. 10. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 10.  1.  0.]
 [ 0.  0.  0. ...  1. 10.  1.]
 [ 0.  0.  0. ...  0.  1.  1.]]
Значения -  [100.  99.  98.  97.  96.  95.  94.  93.  92.  91.  90.  89.  88.  87.
  86.  85.  84.  83.  82.  81.  80.  79.  78.  77.  76.  75.  74.  73.
  72.  71.  70.  69.  68.  67.  66.  65.  64.  63.  62.  61.  60.  59.
  58.  57.  56.  55.  54.  53.  52.  51.  50.  49.  48.  47.  46.  45.
  44.  43.  42.  41.  40.  39.  38.  37.  36.  35.  34.  33.  32.  31.
  30.  29.  28.  27.  26.  25.  24.  23.  22.  21.  20.  19.  18.  17.
  16.  15.  14.  13.  12.  11.  10.   9.   8.   7.   6.   5.   4.   3.
   2.   1.]
Лямбда минимальная  =  0.8888888888888881 
 Лямбда максиммальная =  12.007560287214318
Число обусловленности =  32.17168332809065
Список значений аргументов =  
 [-3.45745028e+02  4.40191782e+01  4.55324589e+00  8.44836296e+00
  7.96312452e+00  7.92039185e+00 

In [42]:
import matplotlib.pyplot as plt
import numpy as np
import math as m
import sympy as sp

def matrix(): #Функция задания матрицы 
    coef_a = 10.
    A = np.zeros((100, 100))
    F = np.zeros(100)
    for i in range(0,100,1):
        F[i] = 100 - i
        for j in range(0,100,1):
            if(i == 0):
                A[i][j] = 1
            elif((i > 0) & (i <= 98)):
                if(i == j):
                    A[i][j] = coef_a * 1.
                    A[i][j-1] = 1.
                    A[i][j+1] = 1.
                    continue
            else:
                if(j > 97):
                    A[i][j] = 1.
    return A, F
A,F = matrix() #Задание матрицы

print("Матрица коэффициентов - ",'\n',A)
print("Значения - ",F)

save = 1 # используется для вычесления точности

m = np.linalg.norm(A, 1) * np.linalg.norm(np.linalg.inv(A) , 1) # вычесление числа обусловленности  

E = 10 ** -6  # Задаем точность

while(abs(-save + X[0]) > E):# Метод Якоби-Гаусса
    
    save = X[0]
    for i in range(100):
        sum1 = 0.
        for j in range(100):
            if(i != j):
                sum1 += A[i][j] * X[j]
        X[i] = 1. / A[i][i] * (F[i] - sum1)

lambdmin = 1000000000000 # Перемнная для лямбда минимальное
lambdmax = -1000000000000 # Переменная для лямбда максимальное

lambds = list() # задание пустого списка всех лямбд
lambds = np.linalg.eig(A) # задания списка всех лямбд

def lmbd(A, N):
    w0 = np.zeros(100)#
    w0[0] = 1.
    summ = 0.
    w0norm = np.zeros(100)
    e = 1
    w = np.zeros(100)
    while (e > 0.00001):
        for i in range (N):
            summ = summ + w0[i] * w0[i]

        d0 = sqrt(summ)

        for i in range(N):
            w0norm[i] = w0[i] / d0

        for i in range(N):
            w[i] = 0
            for j  in range(N):
                w[i] = w[i] + A[i][j] * w0norm[j]

        summ = 0
        for i in range(100):
            summ = summ + w[i] * w[i]
        d = sqrt(summ);

        e = abs(d - d0)
        for i in range(100):
            w0[i] = w[i]
        summ = 0
    print("Лямбда максимальная без библиотеки = ", d)
lmbd(A,100)

for i in (lambds[0]): # нахождение минимальной и максимальной лямбды
    if (i >= lambdmax):
        lambdmax = i
    if(i <= lambdmin):
        lambdmin = i
        
R = abs(np.dot(A, X) - F) # Нахождение вектора невязки
   
print("Лямбда минимальная  = ", lambdmin,"\t",  "Лямбда максиммальная = ", lambdmax)
print ("Число обусловленности = ",m)
print("Список значений аргументов = ","\n", X) 
print("Вектор невязки = ","\n", np.linalg.norm(R,1))



Матрица коэффициентов -  
 [[ 1.  1.  1. ...  1.  1.  1.]
 [ 1. 10.  1. ...  0.  0.  0.]
 [ 0.  1. 10. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 10.  1.  0.]
 [ 0.  0.  0. ...  1. 10.  1.]
 [ 0.  0.  0. ...  0.  1.  1.]]
Значения -  [100.  99.  98.  97.  96.  95.  94.  93.  92.  91.  90.  89.  88.  87.
  86.  85.  84.  83.  82.  81.  80.  79.  78.  77.  76.  75.  74.  73.
  72.  71.  70.  69.  68.  67.  66.  65.  64.  63.  62.  61.  60.  59.
  58.  57.  56.  55.  54.  53.  52.  51.  50.  49.  48.  47.  46.  45.
  44.  43.  42.  41.  40.  39.  38.  37.  36.  35.  34.  33.  32.  31.
  30.  29.  28.  27.  26.  25.  24.  23.  22.  21.  20.  19.  18.  17.
  16.  15.  14.  13.  12.  11.  10.   9.   8.   7.   6.   5.   4.   3.
   2.   1.]
Лямбда максимальная без библиотеки =  12.0036305703594
Лямбда минимальная  =  0.8888888888888881 	 Лямбда максиммальная =  12.007560287214318
Число обусловленности =  32.17168332809065
Список значений аргументов =  
 [-3.45745028e+02  4.40191782e+01  4.5532458

In [50]:
from sympy import *
from sympy.abc import l
import random
import numpy as np
import matplotlib.pyplot as plt # Метод хорд, №1


def matrix(): #Функция задания матрицы 
    coef_a = 10.
    A = np.zeros((100, 100))
    F = np.zeros(100)
    for i in range(0,100,1):
        F[i] = 100 - i
        for j in range(0,100,1):
            if(i == 0):
                A[i][j] = 1
            elif((i > 0) & (i <= 98)):
                if(i == j):
                    A[i][j] = coef_a * 1.
                    A[i][j-1] = 1.
                    A[i][j+1] = 1.
                    continue
            else:
                if(j > 97):
                    A[i][j] = 1.
    return A
A = matrix() #Задание матрицы
print(A)
lambdmax = -10000000 # Переменная для лямбда максимальное
lambdmin = 10000000

def schmidt(A):
    Q=np.zeros_like(A)
    cnt = 0
    for a in A.T: # перебор по транспонированной матрице А
        u = np.copy(a)
        for i in range(0, cnt):
            u -= np.dot(np.dot(Q[:, i].T, a), Q[:, i]) # находим u               
        e = u / np.linalg.norm(u)  # нормализуем и
        Q[:, cnt] = e #сохраняем столбцы
        cnt += 1
    R = np.dot(Q.T, A) # находим R
    return (Q, R)
def lm(A): # метод нахождения лямбды на доп задание
    Ag = A.copy()
    (Q, R) = schmidt(Ag)
    for i in range(len(A) * 5):
        (Q, R) = schmidt(Ag)
        Ag = np.dot(R, Q)
    
    
    
    lambdmax = -1000000000000 # Переменная для лямбда максимальное
    lambdmin = 1000000000000
    for i in range(len(Ag[0])):
        if lambdmax <= Ag[i][i]:
            lambdmax = Ag[i][i]
        if lambdmin >= Ag[i][i]:
            lambdmin = Ag[i][i]
    
    print("Лямбда максимальная  = ", lambdmax, " ","Лямбда минимальная  = ",  lambdmin,'\n', "Посчитаны через QR разложение по методу Грама - Шмидта ")

    




lambds = list() # задание пустого списка всех лямбд
lambds = np.linalg.eig(A) # задания списка всех лямбд

lambdmax = -10000000 # Переменная для лямбда максимальное
lambdmin = 10000000
for i in (lambds[0]): # нахождение минимальной и максимальной лямбды
    if (i <= lambdmin):
        lambdmin = i
    if (i >= lambdmax):
        lambdmax = i
print("Лямбда максимальная библиотечная -",lambdmax, "\t", "Лямбда минимальная библиотечная -", lambdmin)
lm(A)


    

[[ 1.  1.  1. ...  1.  1.  1.]
 [ 1. 10.  1. ...  0.  0.  0.]
 [ 0.  1. 10. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... 10.  1.  0.]
 [ 0.  0.  0. ...  1. 10.  1.]
 [ 0.  0.  0. ...  0.  1.  1.]]
Лямбда максимальная библиотечная - 12.007560287214318 	 Лямбда минимальная библиотечная - 0.8888888888888881
Лямбда максимальная  =  12.000479421002456   Лямбда минимальная  =  0.8888888889053939 
 Посчитаны через QR разложение по методу Грама - Шмидта 


In [7]:
import matplotlib.pyplot as plt
import numpy as np
import math as m
import sympy as sp

 #Функция задания матрицы 
coef_a = 10
save = -1 # используется для вычесления точности 

E = 10 ** -16  # Задаем точность

F = np.zeros(100)
X = np.zeros(100)
count = 0
scroll = 0
for i in range(0,100,1):
    F[i] = 100 - i
X0 = 1000
    
while(abs(-save + X0) > E):# Метод Якоби-Гаусса с ограничением по памяти
    
    A = np.zeros(100)
    for j in range(0,100,1):
        if(count == 0):
            A[j] = 1
        elif((count > 0) & (count <= 98)):
            if(count == j):
                A[j] = coef_a * 1.
                A[j-1] = 1.
                A[j+1] = 1.
                continue
        else:
            if(j > 97):
                A[j] = 1.
    
    sum1 = 0.
    for j in range(100):
        if(count != j):
            sum1 += A[j] * X[j]
    X[count] = 1. / A[count] * (F[count] - sum1)
    if (count == 0):
        save = X0
    X0 = X[count]
    
    count += 1
    if(count == 100):
        count = 0
        scroll += 1

print("Список значений аргументов = ","\n", X) 

Список значений аргументов =  
 [-3.45745028e+02  4.40191782e+01  4.55324589e+00  8.44836296e+00
  7.96312452e+00  7.92039185e+00  7.83295701e+00  7.75003802e+00
  7.66666283e+00  7.58333372e+00  7.49999996e+00  7.41666667e+00
  7.33333333e+00  7.25000000e+00  7.16666667e+00  7.08333333e+00
  7.00000000e+00  6.91666667e+00  6.83333333e+00  6.75000000e+00
  6.66666667e+00  6.58333333e+00  6.50000000e+00  6.41666667e+00
  6.33333333e+00  6.25000000e+00  6.16666667e+00  6.08333333e+00
  6.00000000e+00  5.91666667e+00  5.83333333e+00  5.75000000e+00
  5.66666667e+00  5.58333333e+00  5.50000000e+00  5.41666667e+00
  5.33333333e+00  5.25000000e+00  5.16666667e+00  5.08333333e+00
  5.00000000e+00  4.91666667e+00  4.83333333e+00  4.75000000e+00
  4.66666667e+00  4.58333333e+00  4.50000000e+00  4.41666667e+00
  4.33333333e+00  4.25000000e+00  4.16666667e+00  4.08333333e+00
  4.00000000e+00  3.91666667e+00  3.83333333e+00  3.75000000e+00
  3.66666667e+00  3.58333333e+00  3.50000000e+00  3.416666

In [ ]:
[-3.45745028e+02  4.40191782e+01  4.55324589e+00  8.44836296e+00
  7.96312452e+00  7.92039185e+00  7.83295701e+00  7.75003802e+00
  7.66666283e+00  7.58333372e+00  7.49999996e+00  7.41666667e+00
  7.33333333e+00  7.25000000e+00  7.16666667e+00  7.08333333e+00
  7.00000000e+00  6.91666667e+00  6.83333333e+00  6.75000000e+00
  6.66666667e+00  6.58333333e+00  6.50000000e+00  6.41666667e+00
  6.33333333e+00  6.25000000e+00  6.16666667e+00  6.08333333e+00
  6.00000000e+00  5.91666667e+00  5.83333333e+00  5.75000000e+00
  5.66666667e+00  5.58333333e+00  5.50000000e+00  5.41666667e+00
  5.33333333e+00  5.25000000e+00  5.16666667e+00  5.08333333e+00
  5.00000000e+00  4.91666667e+00  4.83333333e+00  4.75000000e+00
  4.66666667e+00  4.58333333e+00  4.50000000e+00  4.41666667e+00
  4.33333333e+00  4.25000000e+00  4.16666667e+00  4.08333333e+00
  4.00000000e+00  3.91666667e+00  3.83333333e+00  3.75000000e+00
  3.66666667e+00  3.58333333e+00  3.50000000e+00  3.41666667e+00
  3.33333333e+00  3.25000000e+00  3.16666667e+00  3.08333333e+00
  3.00000000e+00  2.91666667e+00  2.83333333e+00  2.75000000e+00
  2.66666667e+00  2.58333333e+00  2.50000000e+00  2.41666667e+00
  2.33333333e+00  2.25000000e+00  2.16666667e+00  2.08333333e+00
  2.00000000e+00  1.91666667e+00  1.83333333e+00  1.75000000e+00
  1.66666667e+00  1.58333333e+00  1.50000000e+00  1.41666667e+00
  1.33333333e+00  1.25000000e+00  1.16666667e+00  1.08333333e+00
  1.00000000e+00  9.16666667e-01  8.33333332e-01  7.50000009e-01
  6.66666577e-01  5.83334220e-01  4.99991223e-01  4.16753553e-01
  3.32473251e-01  2.58513941e-01  8.23873399e-02  9.17612660e-01]